version: '3.1'

services:

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: booking
      MYSQL_USER: booking
      MYSQL_PASSWORD: booking
      TZ: Europe/Budapest
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
  
volumes:
  mysql_volume: